<?php
define('TBL_USER','user');
define('TBL_CATEGORY_MASTER','category_master');
define('TBL_CATEGORY_DESCRIPTION','category_description');
define('TBL_LANGUAGE','language');
define('TBL_PRODUCT','product');
define('TBL_PRODUCT_TO_CATEGORY','product_to_category');
define('TBL_PRODUCT_TO_IMAGE','product_to_image');
define('TBL_COUNTRY','countries');
define('TBL_STATE','states');
define('TBL_ADD_TO_FAVORITE','favorite');
define('TBL_CART_MASTER','cart_master');
define('TBL_CART_DETAILS','cart_details');
define('TBL_ADDRESS_BOOK','address_book');
define('TBL_PRODUCT_OPTION_MASTER','product_option_master');
define('TBL_PRODUCT_OPTION_DETAIL','product_option_detail');
define('TBL_SELLER_STORE','seller_store');
define('TBL_PRODUCT_REVIEW','product_review');
define('TBL_PRODUCT_TO_PRODUCT_OPTION','product_to_product_options');
?>